server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ron19102004@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240MB
      max-request-size: 10240MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: Food-Delivery
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://fooddelivery-ron19102004-0d8a.k.aivencloud.com:21634/defaultdb
    username: avnadmin
    password: AVNS_vkJBZmk6MPZMChTZiY3
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

cloud:
  endpointUrl: https://s3.ap-southeast-2.amazonaws.com
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-southeast-2
    stack:
      auto: false
    bucket:
      name: fooddelivery-123
constant:
  images:
    default:
      avatar: https://cdn-icons-png.flaticon.com/512/6596/6596121.png
      category: https://image.pngaaa.com/854/6338854-middle.png
      food: https://img.freepik.com/free-photo/hands-holding-knife-fork-alarm-clock-plate-blue-background_169016-21525.jpg
      seller-bg: https://image.slidesdocs.com/responsive-images/background/illustrated-3d-render-of-hotdog-vendor-street-takeaway-food-powerpoint-background_018acabab4__960_540.jpg