server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ron19102004@gmail.com
    password: yolinxdflfxnkcuc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240MB
      max-request-size: 10240MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: Food-Delivery
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_delivery_app
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

cloud:
  endpointUrl: https://s3.ap-southeast-2.amazonaws.com
  aws:
    credentials:
      access-key: AKIAQ3EGWTN6CXOVNZMO
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false
    bucket:
      name: food-delivery-ron-app
constant:
  images:
    default:
      avatar: https://cdn-icons-png.flaticon.com/512/6596/6596121.png
      category: https://image.pngaaa.com/854/6338854-middle.png
      food: https://img.freepik.com/free-photo/hands-holding-knife-fork-alarm-clock-plate-blue-background_169016-21525.jpg